FROM node:22

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the project files
COPY . .

# Expose CRA default port
EXPOSE 3000

# Start the React development server
CMD ["npm", "start"]
